### ISSUE TITLE
select empty string in dropdown list

### ISSUE THREAD

**Issue by j-nord** [syncfusion/ej2-ng-dropdowns#2]
Hi,

it is not possible to specify an empty selection "". The empty selection is not displayed. This was still possible under js1.

value: "" text: ""  <-- empty string that can be selected
value: "Herr" text: "Herr"
value: "Frau" text: "Frau"
value: "Firma" text: "Firma"

Regards

j.nord

**Comment by rajendranr-5483** [comment]
@j-nord, We have confirmed that the issue “List item with blank value is not displayed” is a defect at our end and we have logged a defect report. The fix for this issue is estimated to be available on upcoming release which is expected to be rolled out on 1st Dec 2017. Meanwhile, you can resolve this issue by overriding the list item style. For your convenience, we have prepared in Plunker. In this sample, we have used a list item with empty string with space. Sample: [EJ2-DropDownList-select](http://plnkr.co/edit/vSW4KAQdkO4NE0j6FOq4?p=preview)

**Comment by j-nord** [comment]
How can we find the update from 1st Dec 2017 ?

**Comment by saravanangn** [comment]
Hi @j-nord,
We are fixed you reported issue and rolled out in v15.4.20-preview release. Now, you can upgrade the ej2-ng-dropdowns npm package on your application.  

NPM package: https://www.npmjs.com/package/@syncfusion/ej2-ng-dropdowns  

**Note: -** Kindly add watch this repository, so you will get notify for each patch and main release.

Please let us know, if you have any other concern, we will happy to assist you. 

Regards, 
Saravanan G

**Comment by j-nord** [comment]
Thanks,

with the version 15.4.20 it works fine.

Regards
j.nord
