### ISSUE TITLE
Floating label not working properly with ComboBox component

### ISSUE THREAD

**Issue by PH4RA0H** [syncfusion/ej2-ng-dropdowns#4]
Hello,

The floating label on combo box component (placeholder) shows behind the value of the control.

Plunker that shows the issue:
http://plnkr.co/edit/E90a7b4ZuLf0s48TYyjL?p=preview

The issue is present on other dropdown list component albeit the behaviour is slightly different (the label never goes into floating position).  Only tested these two components so maybe it would be worthwhile to check other similar components.

Cheers!

**Comment by Gopigovin** [comment]
Dear Customer,

Thank you for using Syncfusion EJ2 components.

We have analyzed your code sample; the floating label issue is occurred due to property value casing is mismatched. In your sample “**floatLabelType**” API value are in “auto”, but it should be “**Auto**”. We have modified the your sample 
-  http://plnkr.co/edit/0ndM32zAHw64nLf1oKDi?p=preview 

**API reference**:  http://ej2.syncfusion.com/15.4.23/angular/documentation/combo-box/api-comboBoxComponent.html#floatlabeltype

We have ensured **floatLabelType** in all DropDowns controls it’s working good. 

Please let us know, if you have any other concern, we will happy to assist you.

Regards,
Gopi G.

**Comment by PH4RA0H** [comment]
Hello and thanks for looking into the issue,

You are correct and it was indeed my oversight in casing causing the problem for which I apologize. This fixes the issue so I will close this issue requiest.
